language: java

jdk:
  - openjdk14

services:
  - postgresql

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:

    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN=""